# Snazzy color scheme for Kitty

foreground            #eff0eb
background            #282a36
selection_foreground  #eff0eb
selection_background  #3e404a
cursor                #97979b

# Black
color0   #282a36
color8   #686868

# Red
color1   #ff5c57
color9   #ff5c57

# Green
color2   #5af78e
color10  #5af78e

# Yellow
color3   #f3f99d
color11  #f3f99d

# Blue
color4   #57c7ff
color12  #57c7ff

# Magenta
color5   #ff6ac1
color13  #ff6ac1

# Cyan
color6   #9aedfe
color14  #9aedfe

# White
color7   #f1f1f0
color15  #eff0eb
